blog/urls.py
from django.urls import path
# Importo las vistas que estan en este directorio
from . import views

urlpatterns = [
    path('', views.blog, name='blog'),
    path('category/<int:category_id>/', views.category, name='category'),
]

webempresa/urls.py
from django.contrib import admin
from django.urls import path

# Esto va a importar de nuestro fichero core las vistas basicas
from django.urls import include, path

# Extendiendo las funciones en modo de depuracion y ver static - media
from django.conf import settings

urlpatterns = [
    # Paths del core
    path('', include('core.urls')),
    # Paths del Contact
    path('contact/', include('contact.urls')),
    # Paths de Services
    path('services/', include('services.urls')),
    # Paths de Services
    path('blog/', include('blog.urls')),
    # Paths de Pages
    path('page/', include('pages.urls')),
    # Paths del admin
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    # Para ver los archivos estaticos
    from django.conf.urls.static import static

    # Se agrega las direcciones para visualizar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
# Manejo de Fechas
from django.utils.timezone import now
# Acceso a usuarios
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name = "Nombre")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name = "Fecha de Edición")

    class Meta: 
        verbose_name = "categoría"
        verbose_name_plural = "categorías"
        ordering = ["-created"]  

    def __str__(self):
        return "%s %s" % (self.name, self.created)


class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name = "Título")
    content = models.TextField(verbose_name = "Contenido")
    published = models.DateTimeField(verbose_name = "Fecha de Publicación", default=now)
    image = models.ImageField(verbose_name = "Imagen", upload_to="blog", null=True, blank=True)
    author = models.ForeignKey(User, verbose_name = "Autor", on_delete=models.CASCADE)
    categories = models.ManyToManyField(Category, verbose_name = "categorías", related_name="get_posts")
    created = models.DateTimeField(auto_now_add=True, verbose_name = "Fecha de Creación")
    updated = models.DateTimeField(auto_now=True, verbose_name = "Fecha de Edición")

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "entrada"
        verbose_name_plural = "entradas"
        ordering = ["-created"] 

blog/views.py
from django.shortcuts import render, get_object_or_404
# Se agrega el modelo
from .models import Post, Category

# Create your views here.
def blog(request):
    # Con el ORM de Django se obtienen los datos en objetos
    posts = Post.objects.all()
    return render(request, "blog/blog.html", {'posts':posts})


def category(request, category_id):
    category = get_object_or_404(Category, id=category_id)
    # posts = Post.objects.filter(categories=category)
    # return render(request, "blog/category.html", {'category':category, 'posts':posts})
    return render(request, "blog/category.html", {'category':category})

blog/templates/blog/blog.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Blog{% endblock %}

{% block message %}
  {% for post in posts %}
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-innerv text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">{{post.published|date:"SHORT_DATE_FORMAT"}}</span>
                <span class="section-heading-lower">{{post.title}}</span>
              </h2>
              <p class="mb-0">
                <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt="">
              </p>
              <p class="mb-0 mbt">
                {{post.content|linebreaks}}
              </p>
              <p class="mb-0 mbt">
                <span class="section-heading-under">Publicado por 
                  <em><b>{{post.author}}</b></em> en 
                  <em>
                    {% comment %} <a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em> {% endcomment %}
                    {% comment %} {{post.categories.all}} {% endcomment %}
                    {% for category in post.categories.all %}
                        {{category.name}}{% if not forloop.last %},{% endif %}
                    {% endfor %}
                  </span>
              </p>
            </div>

          </div>
        </div>
      </div>
    </section>
  {% endfor %} 
{% endblock %}

blog/templates/blog/category.html
{% extends "core/base.html" %}
{% load static %}

{% block title %}Blog{% endblock %}

{% block message %}
  {% comment %} {% for post in posts %} {% endcomment %}
  {% comment %} {% for post in category.post_set.all %} {% endcomment %}
  {% for post in category.get_posts.all %}
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-innerv text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">{{post.published|date:"SHORT_DATE_FORMAT"}}</span>
                <span class="section-heading-lower">{{post.title}}</span>
              </h2>
              <p class="mb-0">
                <img class="mx-auto d-flex rounded img-fluid mb-3 mb-lg-0" src="{{post.image.url}}" alt="">
              </p>
              <p class="mb-0 mbt">
                {{post.content|linebreaks}}
              </p>
              <p class="mb-0 mbt">
                <span class="section-heading-under">Publicado por 
                  <em><b>{{post.author}}</b></em> en 
                  <em>
                    {% comment %} <a href="#" class="link">General</a>, <a href="#" class="link">Ofertas</a></em> {% endcomment %}
                    {% comment %} {{post.categories.all}} {% endcomment %}
                    {% for category in post.categories.all %}
                        <a href="{% url 'category' category.id %}" class="link">{{category.name}}</a>{% if not forloop.last %},{% endif %}
                    {% endfor %}
                  </em>
                </span>
              </p>
            </div>

          </div>
        </div>
      </div>
    </section>
  {% endfor %} 
{% endblock %}